### ISSUE TITLE
Avoid dependencies

### ISSUE THREAD

**Issue by soypat** [Southclaws/fault#12]
So there's nothing wrong with using testify/assert library if it floats your boat- though I feel there is so little use of it that the whole dependency could be ditched. Like ol' Go proverbs saying goes: a little copying is better than a little dependency :)

I can contribute this feature as I feel `fault` might have a big future ahead of itself. Awesome library by the way!

**Comment by Southclaws** [comment]
Hey, thanks for point this issue out! I completely agree.

I'm moving the tests into a separate module so the root doesn't need to depend on all the test libraries. It'll also be testing against pkg/errors and various other error libraries so I definitely do not want to pollute the supply chain with these unnecessary dependencies.

See #10 for progress on this.

**Comment by Southclaws** [comment]
[The package now has a beautifully empty go.mod](https://github.com/Southclaws/fault/blob/master/go.mod) ✨
