### ISSUE TITLE
Support multiple ftag

### ISSUE THREAD

**Issue by matdurand** [Southclaws/fault#34]
Hey,

While using the lib, I discoved that it would be useful to support multiple ftags. Fault already allows me to set multiple ftags (Security being a custom one in this example)
```
err = fault.Wrap(err,
		fmsg.WithDesc("User not found", "Cannot find the requested user"),
		ftag.With(ftag.NotFound),
		ftag.With(Security))
```
but the API to get them only return the first tag. This is confusing since the code above is valid.
```
tag := ftag.Get(err) // will return Security in this case
```

If you define the solution, I can create a pull request.

**Comment by matdurand** [comment]
I understand your point of view, but I would argue that returning the "first" or highest tag is actually less simple because you're taking a stance and implementing a logic. To me the problem is that there is a discrepancy in fault's api in that it allows you to store multiple tags, but it only returns the highest one. If you want ftag to be simpler, returning everything makes more sense. Then the caller can decide to get the "highest" or first.

I will implement a function for this. Thanks for the code. Feel free to close this issue.

**Comment by Southclaws** [comment]
This makes sense, by simple I meant that of the API not the implementation, and it's quite opinionated by design though the actual interface of Fault being `func(error) error` means you can implement any kind of functionality you need.

While I won't introduce a breaking change to the `Get` method, feel free to open a PR to implement the GetAll method.

**Comment by matdurand** [comment]
We can close this issue now. Could you make a release so I can use the GetAll function plz. Thanks!

**Comment by Southclaws** [comment]
Oh yeah, will do!
